### ISSUE TITLE
docs!

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/create-nteract-app#20]
We should get some docs going 😄. 

I am not sure what format, but we could consider:
- a user guide
- a simple static site (maybe even built with create-nteract-app? 🤪)
- even just improving the readme

However it goes, some things I think it might be nice for folks to learn:
- what the basic structure of a create-nteract-app app is
- the fact that pages can be built using jsx or mdx
- how styling works (styled-jsx currently)
- how to add typing with flow
- information about building/deploying their app
- maybe even some simple example apps bootstrapped with create-nteract-app

**Comment by willingc** [comment]
@rgbkrk I would like to consolidate all the docs into pages of the main nteract website. 

@alexandercbooth Let's iterate on the README first as that content will be needed later. So happy this is moving forward.

**Comment by alexandercbooth** [comment]
That's a great idea @willingc, I'll try to get a README PR going this weekend 👍

**Comment by rgbkrk** [comment]
>  I would like to consolidate all the docs into pages of the main nteract website.

I totally agree with that.
