### ISSUE TITLE
consider including testing in cna

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/create-nteract-app#21]
Should we consider adding Jest as a dependency in the template and include a basic test in the same way [create-react-app](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/template/src/App.test.js) does?

It might be good to impose a best practice by default, but it would also make our dependencies larger 🤔.

**Comment by rgbkrk** [comment]
I can't imagine `jest` being too huge, this seems like a good practice. 😄
