### ISSUE TITLE
built unchanged app...does not run

### ISSUE THREAD

**Issue by jefftrevino** [nteract/create-nteract-app#27]
I ran this sequence of commands:

```
npm i -g create-nteract-app
create-nteract-app 
create-nteract-app firstMeetingApp
cd firstMeetingApp/
yarn build
yarn start
```

The final built app fails when loaded, with the following error.
<img width="1375" alt="screen shot 2018-09-12 at 1 57 04 pm" src="https://user-images.githubusercontent.com/716685/45452934-2eb79b80-b694-11e8-9e79-b335aca13be5.png">

**Comment by rgbkrk** [comment]
Same as #19. Not @jefftrevino's fault for reporting it extra since I just told him to in person.
